DTNN-132 Add full test

diff --git a/docs/example_scripts/build-bp b/docs/example_scripts/build-bp
--- a/docs/example_scripts/build-bp
+++ b/docs/example_scripts/build-bp
@@ -1,6 +1,13 @@
+#!/bin/bash
+build-bp-err() {
+   echo "build-bp exited on error."
+   exit 1
+}
+trap build-bp-err ERR
+
    cd $HOME/build
-   make DESTDIR=.. -j2 mission-install
-   cd ../exe
-   tar -cvf ../cfs-bpapp.tar .
-   cd ..
+   make DESTDIR=$HOME/cfs-build-folder -j2 mission-install
+   cd $HOME/cfs-build-folder/exe
+   tar -cvf $HOME/cfs-bpapp.tar .
+   cd $HOME
    ls -l cfs-bpapp.tar
diff --git a/docs/example_scripts/clean-bp b/docs/example_scripts/clean-bp
--- a/docs/example_scripts/clean-bp
+++ b/docs/example_scripts/clean-bp
@@ -1,3 +1,11 @@
-#!/bin/bash -x
-rm -rf bpxfer_defs/ build/ cfs-bundle/ cfs-bpapp.tar exe \
-tinycbor-source/ tinycbor-staging/
+#!/bin/bash
+clean-bp-err() {
+   echo "clean-bp exited on error."
+   exit 1
+}
+trap clean-bp-err ERR
+set -x
+
+   rm -rf bpxfer_defs/ build/ host cfs-bundle/ cfs-bpapp.tar cfs-build-folder exe \
+   rx tx tinycbor-source/ tinycbor-staging/
+
diff --git a/docs/example_scripts/install-toolchain b/docs/example_scripts/install-toolchain
--- a/docs/example_scripts/install-toolchain
+++ b/docs/example_scripts/install-toolchain
@@ -1,4 +1,10 @@
 #!/bin/bash
+install-toolchain-err() {
+   echo "install-toolchain exited on error."
+   exit 1
+}
+trap install-toolchain-err ERR
+
    cd $HOME
    sudo apt update
    sudo apt upgrade
diff --git a/docs/example_scripts/prep-bp-build b/docs/example_scripts/prep-bp-build
--- a/docs/example_scripts/prep-bp-build
+++ b/docs/example_scripts/prep-bp-build
@@ -1,4 +1,10 @@
 #!/bin/bash
+prep-bp-build-err() {
+   echo "prep-bp-build exited on error."
+   exit 1
+}
+trap prep-bp-build-err ERR
+
    cd $HOME
    git clone https://github.com/nasa/cFS.git cfs-bundle
    pushd cfs-bundle
